### ISSUE TITLE
Set file version on DLL

### ISSUE THREAD

**Issue by frankschmitt** [xanthidae/xanthidae#6]
Currently, the generated DLL contains no file version info. This causes several issues:
- in Windows Explorer, you cannot simply check the file version 
- the Help > Check for updates page shows "1899-12-30" as the plugin file version, which is clearly nonsensical

Presumably, we could use [Winres](https://github.com/mxre/winres) to achieve this.

**Comment by marcoerdmann** [comment]
Properties of DLL after configuration of `winres`:

![image](https://user-images.githubusercontent.com/13285180/173498295-7e90853b-6317-4645-9e1d-ecb9c717ddfc.png)
